### ISSUE TITLE
some thing wrong

### ISSUE THREAD

**Issue by fanly** [cuzv/Redes#1]
FAILURE: Error Domain=com.alamofire.error Code=-9999 "Server response llegal" UserInfo={NSLocalizedFailureReason=Server response llegal}
"Request deinit..."
"AlamofireCommand deinit..."

codes:

func performLogin() {
        let loginApi = LoginApi(tel: "****_", password: "**_*")
        Redes.request(loginApi).responseJSON {
            debugPrint($0)
        }
    }

**Comment by cuzv** [comment]
This sample code **will not work** untill you setup your server api configuration in `API.swift` file.
In other words, since everyone server have different api contract, you should implement `protocol<Requestable, Responseable>` setups you self.
Just please checkout the `API.swift` file, you will get it, :]
